name_db = "minhashdb"
user = "postgres"
password = "1234"
host = "localhost"
port = "5432"
# host = "127.0.0.1"
filename = r"minhash_data3.csv"
filename_update = r"update_minhash.csv"
count_shuffle = 1000
len_of_buck = 100
